# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    annotations: false
    http_method_override: false
    handle_all_throwables: true

    # Trust reverse proxy headers (Traefik)
    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port']

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        cookie_httponly: true
        gc_maxlifetime: 3600

    #esi: true
    #fragments: true
    php_errors:
        log: true

    # Rate Limiting f√ºr Login-Schutz
    rate_limiter:
        # Eltern-Login: 5 Versuche pro Minute pro IP
        parent_login:
            policy: 'sliding_window'
            limit: 5
            interval: '1 minute'
            lock_factory: 'lock.factory'
        # Admin-Login: 5 Versuche pro Minute pro IP
        admin_login:
            policy: 'sliding_window'
            limit: 5
            interval: '1 minute'
            lock_factory: 'lock.factory'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
